import { TProject } from "@/interface";

export const projects: TProject[] = [
  {
    title: "Share Space",
    slug: "share-space",
    category: "FullStack",
    image: "/images/projects/share-space-1.PNG",
    live: "https://share-space-tangail.vercel.app/",
    githubLink: "https://github.com/AhmadShopnil/ShareSpace-client__Prod",
    description: "A full-stack application for renting properties in Tangail.",
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Prisma",
      "PostgreSQL",
    ],
    features: [
      "User registration and login",
      "Property search and filter",
      "Property posting for owners",
      "Admin panel for management",
    ],
    role: "Developed both frontend and backend features.",
    challenges: "Ensured responsive design and dynamic filtering.",
    futureScope: "Integrating AI for property recommendations.",
    duration: "4 months",
  },
  {
    title: "Bike Rental",
    slug: "bike-rental",
    category: "FullStack",
    image: "/images/projects/bike-rent-1.PNG",
    live: "https://bike-rent-reactjs.netlify.app/",
    githubLink: "https://github.com/AhmadShopnil/bikeRent-frontEnd-reactJs",
    description: "A platform to rent bikes online with user-friendly booking.",
    technologies: ["React", "Redux", "Node.js", "Express.js", "MongoDB"],
    features: [
      "Bike listing with filtering options",
      "User bookings and rental tracking",
      "Admin dashboard for bike management",
    ],
    role: "Designed and implemented frontend with Redux for state management.",
    challenges: "Optimized the booking workflow for better user experience.",
    futureScope: "Adding coupon codes and user reviews.",
    duration: "3 months",
  },
  {
    title: "OneBitPay",
    slug: "onebitpay",
    category: "FullStack",
    image: "/images/projects/onebitpay-1.PNG",
    live: "https://onebitpay.netlify.app/",
    githubLink: "",
    description: "A payment gateway for easy transactions.",
    technologies: ["React", "Tailwind CSS", "Firebase"],
    features: [
      "Secure payments",
      "Transaction history",
      "User-friendly interface",
    ],
    role: "Built the user interface and integrated Firebase.",
    challenges: "Ensured secure payment transactions and real-time updates.",
    futureScope: "Integrating more payment methods.",
    duration: "2 months",
  },
  {
    title: "E-Bazar",
    slug: "e-bazar",
    category: "FrontEnd",
    image: "/images/projects/e-bazar-1.PNG",
    live: "https://e-bazar2.netlify.app/",
    githubLink: "https://github.com/AhmadShopnil/e-bazar",
    description: "An e-commerce front-end template.",
    technologies: ["React", "Tailwind CSS"],
    features: ["Product listing", "Shopping cart", "Responsive design"],
    role: "Developed the frontend with modern UI principles.",
    challenges: "Maintaining responsiveness across devices.",
    futureScope: "Adding backend integration for live product data.",
    duration: "1 month",
  },
  {
    title: "E-Learning",
    slug: "e-learning",
    category: "FullStack",
    image: "/images/projects/e-learning-1.PNG",
    live: "https://e-learning2.netlify.app/",
    githubLink: "https://github.com/AhmadShopnil/e-learning",
    description: "A platform for learners and instructors.",
    technologies: ["React", "Node.js", "MongoDB"],
    features: [
      "Course creation",
      "Student registration",
      "Interactive learning tools",
    ],
    role: "Developed key features for both learners and instructors.",
    challenges: "Handling complex user permissions.",
    futureScope: "Introducing live classes and certification.",
    duration: "4 months",
  },
  {
    title: "Agency",
    slug: "agency",
    category: "FrontEnd",
    image: "/images/projects/agency-1.PNG",
    live: "https://agency-template-1.netlify.app/",
    githubLink: "",
    description: "A clean, responsive template for agencies.",
    technologies: ["HTML", "CSS", "JavaScript"],
    features: ["Modern design", "Responsive layout", "Smooth animations"],
    role: "Designed and implemented the frontend layout.",
    challenges: "Ensuring pixel-perfect design.",
    futureScope: "Adding a portfolio showcase feature.",
    duration: "2 weeks",
  },
];
